from selenium import webdriver
import selenium
import json
import urllib
import html
import urllib3
import turtle
from selenium.webdriver.common.keys import Keys
import time

driver= webdriver.Chrome()
driver.get("https://ssuet.org/login/index.php")
time.sleep(5)
username=driver.find_element_by_id('username')
username.send_keys('it18-036')
password=driver.find_element_by_id('password')
password.send_keys('Dimension-123')
loginbutton=driver.find_element_by_id('loginbtn')
loginbutton.send_keys(Keys.ENTER)

time.sleep(5)
sidebutton=driver.find_element_by_css_selector('[data-action=toggle-drawer] .icon')
sidebutton.click()
time.sleep(3)
firstcourse=driver.find_element_by_link_text('IT415-BSIT-SP21-0')
firstcourse.click()

firstweek=driver.find_element_by_link_text('15 February - 21 February')
firstweek.click()
time.sleep(1)
secondweek=driver.find_element_by_link_text('22 February - 28 February')
secondweek.click()
time.sleep(1)
thirdweek=driver.find_element_by_link_text('1 March - 7 March')
thirdweek.click()
time.sleep(1)
fourthweek=driver.find_element_by_link_text('8 March - 14 March')
fourthweek.click()
time.sleep(1)
fifthweek=driver.find_element_by_link_text('15 March - 21 March')
fifthweek.click()
time.sleep(1)
sixweek=driver.find_element_by_link_text('22 March - 28 March')
sixweek.click()
time.sleep(1)
sevenweek=driver.find_element_by_link_text('29 March - 4 April')
sevenweek.click()
time.sleep(1)
eightweek=driver.find_element_by_link_text('5 April - 11 April')
eightweek.click()
time.sleep(1)
nineweek=driver.find_element_by_link_text('12 April - 18 April')
nineweek.click()
time.sleep(1)
tenweek=driver.find_element_by_link_text('19 April - 25 April')
tenweek.click()
time.sleep(1)
elevenweek=driver.find_element_by_link_text('26 April - 2 May')
elevenweek.click()
time.sleep(1)
twelweek=driver.find_element_by_link_text('3 May - 9 May')
twelweek.click()
time.sleep(1)
thirtenweek=driver.find_element_by_link_text('10 May - 16 May')
thirtenweek.click()
time.sleep(1)
frtenweek=driver.find_element_by_link_text('17 May - 23 May')
frtenweek.click()
time.sleep(1)
fifteenweek=driver.find_element_by_link_text('24 May - 30 May')
fifteenweek.click()
time.sleep(1)
sixteenweek=driver.find_element_by_link_text('31 May - 6 June')
sixteenweek.click()
time.sleep(1)
seventeen=driver.find_element_by_link_text('7 June - 13 June')
seventeen.click()
time.sleep(1)
eghtteen=driver.find_element_by_link_text('14 June - 20 June')
eghtteen.click()
time.sleep(1)
nineteen=driver.find_element_by_link_text('21 June - 27 June')
nineteen.click()
time.sleep(1)
twentyweek=driver.find_element_by_link_text('28 June - 4 July')
twentyweek.click()
time.sleep(1)



Secondcourse=driver.find_element_by_link_text('IT411-BSIT-SP21-0')
Secondcourse.click()

firstweek=driver.find_element_by_link_text('15 February - 21 February')
firstweek.click()
time.sleep(1)
secondweek=driver.find_element_by_link_text('22 February - 28 February')
secondweek.click()
time.sleep(1)
thirdweek=driver.find_element_by_link_text('1 March - 7 March')
thirdweek.click()
time.sleep(1)
fourthweek=driver.find_element_by_link_text('8 March - 14 March')
fourthweek.click()
time.sleep(1)
fifthweek=driver.find_element_by_link_text('15 March - 21 March')
fifthweek.click()
time.sleep(1)
sixweek=driver.find_element_by_link_text('22 March - 28 March')
sixweek.click()
time.sleep(1)
sevenweek=driver.find_element_by_link_text('29 March - 4 April')
sevenweek.click()
time.sleep(1)
eightweek=driver.find_element_by_link_text('5 April - 11 April')
eightweek.click()
time.sleep(1)
nineweek=driver.find_element_by_link_text('12 April - 18 April')
nineweek.click()
time.sleep(1)
tenweek=driver.find_element_by_link_text('19 April - 25 April')
tenweek.click()
time.sleep(1)
elevenweek=driver.find_element_by_link_text('26 April - 2 May')
elevenweek.click()
time.sleep(1)
twelweek=driver.find_element_by_link_text('3 May - 9 May')
twelweek.click()
time.sleep(1)
thirtenweek=driver.find_element_by_link_text('10 May - 16 May')
thirtenweek.click()
time.sleep(1)
frtenweek=driver.find_element_by_link_text('17 May - 23 May')
frtenweek.click()
time.sleep(1)
fifteenweek=driver.find_element_by_link_text('24 May - 30 May')
fifteenweek.click()
time.sleep(1)
sixteenweek=driver.find_element_by_link_text('31 May - 6 June')
sixteenweek.click()
time.sleep(1)
seventeen=driver.find_element_by_link_text('7 June - 13 June')
seventeen.click()
time.sleep(1)
eghtteen=driver.find_element_by_link_text('14 June - 20 June')
eghtteen.click()
time.sleep(1)
nineteen=driver.find_element_by_link_text('21 June - 27 June')
nineteen.click()
time.sleep(1)
twentyweek=driver.find_element_by_link_text('28 June - 4 July')
twentyweek.click()
time.sleep(1)

Thirdcourse=driver.find_element_by_link_text('IT402-BSIT-SP21-0')
Thirdcourse.click()

firstweek=driver.find_element_by_link_text('15 February - 21 February')
firstweek.click()
time.sleep(1)
secondweek=driver.find_element_by_link_text('22 February - 28 February')
secondweek.click()
time.sleep(1)
thirdweek=driver.find_element_by_link_text('1 March - 7 March')
thirdweek.click()
time.sleep(1)
fourthweek=driver.find_element_by_link_text('8 March - 14 March')
fourthweek.click()
time.sleep(1)
fifthweek=driver.find_element_by_link_text('15 March - 21 March')
fifthweek.click()
time.sleep(1)
sixweek=driver.find_element_by_link_text('22 March - 28 March')
sixweek.click()
time.sleep(1)
sevenweek=driver.find_element_by_link_text('29 March - 4 April')
sevenweek.click()
time.sleep(1)
eightweek=driver.find_element_by_link_text('5 April - 11 April')
eightweek.click()
time.sleep(1)
nineweek=driver.find_element_by_link_text('12 April - 18 April')
nineweek.click()
time.sleep(1)
tenweek=driver.find_element_by_link_text('19 April - 25 April')
tenweek.click()
time.sleep(1)
elevenweek=driver.find_element_by_link_text('26 April - 2 May')
elevenweek.click()
time.sleep(1)
twelweek=driver.find_element_by_link_text('3 May - 9 May')
twelweek.click()
time.sleep(1)
thirtenweek=driver.find_element_by_link_text('10 May - 16 May')
thirtenweek.click()
time.sleep(1)
frtenweek=driver.find_element_by_link_text('17 May - 23 May')
frtenweek.click()
time.sleep(1)
fifteenweek=driver.find_element_by_link_text('24 May - 30 May')
fifteenweek.click()
time.sleep(1)
sixteenweek=driver.find_element_by_link_text('31 May - 6 June')
sixteenweek.click()
time.sleep(1)
seventeen=driver.find_element_by_link_text('7 June - 13 June')
seventeen.click()
time.sleep(1)
eghtteen=driver.find_element_by_link_text('14 June - 20 June')
eghtteen.click()
time.sleep(1)
nineteen=driver.find_element_by_link_text('21 June - 27 June')
nineteen.click()
time.sleep(1)
twentyweek=driver.find_element_by_link_text('28 June - 4 July')
twentyweek.click()
time.sleep(1)

fourthcourse=driver.find_element_by_link_text('IT401-BSIT-SP21-0')
fourthcourse.click()

firstweek=driver.find_element_by_link_text('15 February - 21 February')
firstweek.click()
time.sleep(1)
secondweek=driver.find_element_by_link_text('22 February - 28 February')
secondweek.click()
time.sleep(1)
thirdweek=driver.find_element_by_link_text('1 March - 7 March')
thirdweek.click()
time.sleep(1)
fourthweek=driver.find_element_by_link_text('8 March - 14 March')
fourthweek.click()
time.sleep(1)
fifthweek=driver.find_element_by_link_text('15 March - 21 March')
fifthweek.click()
time.sleep(1)
sixweek=driver.find_element_by_link_text('22 March - 28 March')
sixweek.click()
time.sleep(1)
sevenweek=driver.find_element_by_link_text('29 March - 4 April')
sevenweek.click()
time.sleep(1)
eightweek=driver.find_element_by_link_text('5 April - 11 April')
eightweek.click()
time.sleep(1)
nineweek=driver.find_element_by_link_text('12 April - 18 April')
nineweek.click()
time.sleep(1)
tenweek=driver.find_element_by_link_text('19 April - 25 April')
tenweek.click()
time.sleep(1)
print('s')
elevenweek=driver.find_element_by_link_text('26 April - 2 May')
elevenweek.click()
time.sleep(1)
twelweek=driver.find_element_by_link_text('3 May - 9 May')
twelweek.click()
time.sleep(1)
thirtenweek=driver.find_element_by_link_text('10 May - 16 May')
thirtenweek.click()
time.sleep(1)
frtenweek=driver.find_element_by_link_text('17 May - 23 May')
frtenweek.click()
time.sleep(1)
fifteenweek=driver.find_element_by_link_text('24 May - 30 May')
fifteenweek.click()
time.sleep(1)
sixteenweek=driver.find_element_by_link_text('31 May - 6 June')
sixteenweek.click()
time.sleep(1)
seventeen=driver.find_element_by_link_text('7 June - 13 June')
seventeen.click()
time.sleep(1)
eghtteen=driver.find_element_by_link_text('14 June - 20 June')
eghtteen.click()
time.sleep(1)
nineteen=driver.find_element_by_link_text('21 June - 27 June')
nineteen.click()
time.sleep(1)
twentyweek=driver.find_element_by_link_text('28 June - 4 July')
twentyweek.click()
time.sleep(1)

logdrptown=driver.find_element_by_id('action-menu-toggle-1')
logdrptown.click()

logdrptown=driver.find_element_by_id('action-menu-toggle-1')
logdrptown.click()


time.sleep(1)

logout=driver.find_element_by_link_text('Log out')
logout.click()


time.sleep(3)
driver.close()